tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "anyenv"
brew "gibo"
brew "jq"
brew "peco"
brew "tig"
brew 'tree'
brew 'watch'
brew 'wget'
cask "alfred"
cask "docker"
cask "google-chrome"
cask "karabiner-elements"
cask "visual-studio-code"
