brew "fzf"
brew "git"
brew "mise"
brew "tree"
cask "alfred"
cask "amazon-q"
cask "claude"
cask "discord"
cask "docker-desktop"
cask "font-meslo-for-powerlevel10k"
cask "git-credential-manager"
cask "google-chrome"
cask "karabiner-elements"
cask "notion"
cask "visual-studio-code"

